[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#36454F"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#353935"

# Color used for almost all text.
textColor = "#fff"